name: Build OS Image
on:
  workflow_dispatch:

jobs:
  build-default-image:
    name: Build OS image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: cachix/install-nix-action@v13
        with:
          # Pin because the latest all-hardware profile changes
          # https://github.com/NixOS/nixpkgs/pull/128532
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/c23146505c35a07bafbecf36af4f9ebde2bb7dfd.tar.gz
          extra_nix_config: |
            extra-platforms = aarch64-linux

      - uses: myci-actions/add-deb-repo@8
        with:
          repo: deb http://mirror.csclub.uwaterloo.ca/debian sid main non-free contrib
          repo-name: debian-sid
          keys: 648ACFD622F3D138
          key-server: keyserver.ubuntu.com

      - run: |
          sudo apt -y install qemu-user-static

      - name: Test binfmt
        run: |
          cat /proc/sys/fs/binfmt_misc/qemu-aarch64
          /usr/bin/qemu-aarch64-static --version

      - name: Build SD Image
        run: |
          nix-build '<nixpkgs/nixos>'  \
            -A config.system.build.sdImage \
            -I nixos-config=./configuration.nix \
            --argstr system aarch64-linux \
            --option sandbox false

      - uses: actions/upload-artifact@v2
        with:
          name: sd-image.img
          path: ./result/sd-image/*.img*
